Fruits
filter(Fruits,Expenses>80)
filter(Fruits,Expenses>90 & Sales>90)
filter(Fruits,Expenses==91 & Expenses ==79)
Fruits %>% filter(Expenses>=90 || Sales>80)
Fruits %>% filter(Expenses==79 | Expenses==91)
select(Fruits,Fruit:Sales,-Location)
Fruits %>% group_by(Fruit) %>% summarise(average=sum(Sales,na.rm = TRUE))
Fruits %>% group_by(Fruit) %>% summarise_each(funs(sum,sum),Sales,Profit)

data1 <- read.csv("data1.csv")  
attach(data1)
apply(data1[,c(2:15)],1,sum)

data2<-read.csv("1-4호선승하차승객수.csv")
attach(data2)
tapply(승차,노선번호,sum)
tapply(하차,노선번호,sum)
sapply(data2[,c(3,4)],sum)
aggregate(승차+하차~노선번호,data2,sum)
aggregate(승차~노선번호,data2,sum)  
aggregate(하차~노선번호,data2,sum)
tapply(승차, 노선번호, sum)
Fruits
aggregate(Sales~Fruit,Fruits,mean)
aggregate(Expenses~Fruit,Fruits,max)
aggregate(Profit~Fruit,Fruits,min)
aggregate(Sales~Location,Fruits,mean)
aggregate(Profit~Fruit,Fruits,sum)
aggregate(Sales~Year,Fruits,sum)
aggregate(Expenses~Fruit,Fruits,mean)
aggregate(Profit~Location+Fruit,Fruits,mean)
aggregate(Sales~Location+Year,Fruits,sum)
aggregate(Expenses~Location+Fruit,Fruits,sum)
aggregate(Profit~Location+Year,Fruits,max)

data1<-read.csv("data1.csv")
apply(data1[-1], 2, sum)
apply(data1[-1],1,sum)
apply(data1[,c(10:14)], 2, sum)
apply(data1[,-1],1,sum)
d1<-apply(data1[,c(2,7,12)],2,sum)
d1
d2<-apply(data1[,c(2,7,12)],1,sum)
d2
sapply(data1[,-1], sum)
sapply(data1[,c(10:14)],sum)
sapply(data1[,c(2,7,12)],sum)

data2<-read.csv("1-4호선승하차승객수.csv")
attach(data2)
tapply(승차, 노선번호, sum)
tapply(하차, 노선번호, sum)
apply(data2[,c(3,4)],2,sum)
aggregate(승차+하차~노선번호,data2,mean)
tapply(승차+하차,노선번호,mean)
apply(data2[3],2,max)
tapply(승차+하차,노선번호,min)

aggregate(승차+하차~노선번호,data2,sum)
aggregate(승차~노선번호,data2,sum)
aggregate(하차~노선번호,data2,sum)
aggregate(승차~노선번호,data2,mean)
aggregate(하차~노선번호,data2,min)
aggregate(승차+하차~노선번호,data2,max)
